### ISSUE TITLE
Namespace tool does not work for types in Sourcecode

### ISSUE THREAD

**Issue by RobertvanderHulst** [InfomindsAg/XSharpPowerTools2019#7] opened 2021-09-04 12:19 UTC
When I open your XSharpExamples solution and the Namespace tool then I do not see any types that are defined in sourcecode, only types that are defined in external assemblies. Is that by design ?

I also noticed that the menu points are disabled when I open the X# Runtime solution. 
Hoe exactly are determining when the menu options should be visible ?

Finally, I see that you are still using the external database and you are no using the open database in the X# codemodel assembly.
This means that in a new project nothing will be visible until ~ 5 minutes or until you close and reopen that project.

**Comment by simontaschler** [comment] 2021-09-07 09:26
The Namespace tool only looks for types in the Assemblies table at the moment, hence only results contained in external assemblies are found.

The visibility of the menu points depends on the solution containing at least one X# project. With the X# Runtime solution, you're running into a bug caused by all projects being contained in solution folders.

Both the Namespace tool for local types and the visibility bug will be fixed with the release of the next version.

The use of the external database is only a temporary solution for the moment, we plan on switching to the use of the database in the X# codemodel in the future.

**Comment by RobertvanderHulst** [comment] 2021-09-07 10:06
Simon,
Thanks for the update. You are right, all the projects in this solution are inside solution folders.
If you need help to access the internal database, please let me know.

**Comment by RobertvanderHulst** [comment] 2021-09-08 07:51
Thanks, build 1.3 fixes this.
I also like the Code Browser Results toolwindow. Is that new or did I miss that in the previous build ?
Sometimes a search results in more that one item with the same name (overloads of the same method or function). Could you add the "sourcecode" column to the result window so you can see the differences between the overloads ?

**Comment by simontaschler** [comment] 2021-09-08 07:57
The toolwindow was already included, so you probably missed that.
The sourcecode column is already integrated as a tooltip. If you hover your mouse over a column, except for the file column, it should display the sourcecode in a tooltip

**Closed as completed** 2021-09-08 14:38 UTC
